### ISSUE TITLE
MainActivity.kt:11: add link to github repo

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/github-tutorial#1]
The puzzle `1-d9fab9c7` from #1 has to be resolved: 

https://github.com/ammaratef45/github-tutorial/blob/b1cc091778c6cd3453b47e4e1444b3a16642a6b9/android/app/src/main/java/com/opensource/ammar/githubtutorial/MainActivity.kt#L11-L11

The puzzle was created by @ammaratef45 on 13-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1](https://github.com/ammaratef45/github-tutorial/issues/1), [#2](https://github.com/ammaratef45/github-tutorial/issues/2) are still not solved.

**Comment by Nermeen78** [comment]
please describe this issue in details, which link I should add and where in code?

**Comment by ammaratef45** [comment]
@Nermeen78 We need to add a button in the main screen that opens this repository when clicked.
No design available but make it centred horizontally and aligned to the top vertically.
The button text would be "Show On GitHub"

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#unknown](), [#unknown]().
