### ISSUE TITLE
MainActivity.kt:12: create a webview and show the blog...

### ISSUE THREAD

**Issue by 0pdd** [ammaratef45/github-tutorial#2]
The puzzle `1-88955417` from #1 has to be resolved: 

https://github.com/ammaratef45/github-tutorial/blob/b1cc091778c6cd3453b47e4e1444b3a16642a6b9/android/app/src/main/java/com/opensource/ammar/githubtutorial/MainActivity.kt#L12-L12

The puzzle was created by @ammaratef45 on 13-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#6](https://github.com/ammaratef45/github-tutorial/issues/6) is still not solved.

**Comment by ammaratef45** [comment]
@rultor deploy
